<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dashboard extends CI_Controller
{
	function __construct()
    {
        parent::__construct();
        if ($this->session->userdata('logged')<>1) {
            $this->session->set_flashdata('message', '<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert"><i class="ace-icon fa fa-times"></i></button><strong><i class="ace-icon fa fa-times"></i></strong>Anda Belum Login, Silahkan Login Terlebih Dahulu.<br></div>');
            redirect(site_url('auth'));
        }
        if ($this->session->userdata('is_admin')==FALSE) {
            $this->session->set_flashdata('message', '<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert"><i class="ace-icon fa fa-times"></i></button><strong><i class="ace-icon fa fa-times"></i></strong>Anda Tidak Memiliki Akses ke Halaman Tersebut.<br></div>');
            redirect(site_url('wisata'));
            
        }
        $this->load->library('form_validation');
        $this->load->model('Dashboard_model');

    }

    public function index(){
        
        $data = array(
            'Wisata_bandung' => $this->Dashboard_model->get_wisata('3'),
            'Wisata_barat' => $this->Dashboard_model->get_wisata('2'),
            'Wisata_cimahi' => $this->Dashboard_model->get_wisata('4'),
            'Wisata_kab' => $this->Dashboard_model->get_wisata('1'),
            'Pemilik_total_reg' => $this->Dashboard_model->get_pemilik('1'),
            'Pemilik_total_nreg' => $this->Dashboard_model->get_pemilik('0'),
        );

        $this->load->view('admin/dashboard', $data);

    }

}

/* End of file Admin.php */
/* Location: ./application/controllers/Admin.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-31 14:24:22 */
/* http://harviacode.com */