<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kecamatan_model extends CI_Model
{

    public $table = 'kecamatan';
    public $id = 'id_kec';
    public $order = 'DESC';
    public $id_kota = 'id_kota';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_id_kota()
    {
        $this->db->where('NIP=', $this->session->userdata('NIP'));
        $this->db->limit(1);
        return $this->db->get('kota')->result();
    }

    function get_id_kotaow()
    {
        $this->db->order_by('id_kota', $this->order);
        return $this->db->get('kota')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->or_like('kecamatan.nama_kec', $q);
    $this->db->join('kota', $q='kecamatan.id_kota=kota.id_kota');
    $this->db->join('admin', $q='kota.NIP=admin.NIP');
    $this->db->where('kecamatan.is_delete=', $q='0');
    $this->db->where('kota.NIP=', $q=$this->session->userdata('NIP'));
    
        
    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->order_by($this->id, $this->order);
    $this->db->or_like('kecamatan.nama_kec', $q);
    $this->db->join('kota', $q='kecamatan.id_kota=kota.id_kota');
    $this->db->join('admin', $q='kota.NIP=admin.NIP');
    $this->db->where('kecamatan.is_delete=', $q='0');
    $this->db->where('kota.NIP=', $q=$this->session->userdata('NIP'));


    $this->db->limit($limit, $start);

        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->set('is_delete', '1');
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

}

/* End of file Kecamatan_model.php */
/* Location: ./application/models/Kecamatan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-31 14:20:53 */
/* http://harviacode.com */