<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pemilik_model extends CI_Model
{

    public $table = 'pemilik';
    public $id = 'NIK';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('NIK', $q);
        $this->db->or_like('nama_pemilik', $q);
        $this->db->or_like('tmp_lahir', $q);
        $this->db->where('is_delete', $q='0');
        $this->db->from($this->table);
        return $this->db->count_all_results();
	// $this->db->or_like('tgl_lahir', $q);
	// $this->db->or_like('jk_pemilik', $q);
	// $this->db->or_like('alamat_pemilik', $q);
	// $this->db->or_like('password', $q);
	// $this->db->or_like('email_pemilik', $q);
	// $this->db->or_like('notelp_pemilik', $q);
	// $this->db->or_like('file_ktp', $q);
	// $this->db->or_like('is_active', $q);
    
	
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('NIK', $q);
        $this->db->or_like('nama_pemilik', $q);
           $this->db->or_like('tmp_lahir', $q);
        $this->db->where('is_delete', $q='0');
	// $this->db->or_like('tgl_lahir', $q);
	// $this->db->or_like('jk_pemilik', $q);
	// $this->db->or_like('alamat_pemilik', $q);
	// $this->db->or_like('password', $q);
	// $this->db->or_like('email_pemilik', $q);
	// $this->db->or_like('notelp_pemilik', $q);
	// $this->db->or_like('file_ktp', $q);
	// $this->db->or_like('is_active', $q);
    
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    function total_rows_admin($q = NULL) {
        $this->db->like('pemilik.NIK', $q);
        $this->db->join('wisata', $q='wisata.NIK=pemilik.NIK');
        $this->db->join('kota', $q='wisata.id_kota=kota.id_kota');
        $this->db->where('pemilik.is_delete', $q='0');
        $this->db->where('kota.NIP=', $q=$this->session->userdata('NIP'));
        $this->db->from($this->table);
        return $this->db->count_all_results();
    
    }

    // get data with limit and search
    function get_limit_data_admin($limit, $start = 0, $q = NULL) {
        $this->db->order_by('pemilik.NIK', $this->order);
        $this->db->group_by('pemilik.NIK', $this->order);
        $this->db->like('pemilik.NIK', $q);
        $this->db->join('wisata', $q='wisata.NIK=pemilik.NIK');
        $this->db->join('kota', $q='wisata.id_kota=kota.id_kota');
        $this->db->where('pemilik.is_delete', $q='0');
        $this->db->where('kota.NIP=', $q=$this->session->userdata('NIP'));
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function registasi($id)
    {
        $this->db->set('is_Reg', '1');
        $this->db->where($this->id, $id);
        $this->db->update($this->table);
    }

    // delete data
    function deactive($id)
    {
        $this->db->set('is_active', '0');
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function active($id)
    {
        $this->db->set('is_active', '1');
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }


    function delete($id)
    {
        $this->db->set('is_delete', '1');
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

}

/* End of file Pemilik_model.php */
/* Location: ./application/models/Pemilik_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-31 14:20:54 */
/* http://harviacode.com */