<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Admin_model extends CI_Model
{

    public $table = 'admin';
    public $id = 'NIP';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('is_delete=', '0');
        $this->db->where('level=', '1');
        return $this->db->get($this->table)->result();
    }

    function eksport_data() {
        $this->db->select('NIP, nama, username, alamat, jk, email, no_telp, level, is_delete');
        $this->db->from('admin');
        return $this->db->get();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('NIP', $q);
	// $this->db->or_like('nama', $q);
	// $this->db->or_like('username', $q);
	// $this->db->or_like('password', $q);
	// $this->db->or_like('alamat', $q);
	// $this->db->or_like('jk', $q);
	// $this->db->or_like('email', $q);
	// $this->db->or_like('no_telp', $q);
	// $this->db->or_like('level', $q);
    $this->db->where('is_delete', $q='0');
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('NIP', $q);
	// $this->db->or_like('nama', $q);
	// $this->db->or_like('username', $q);
	// $this->db->or_like('password', $q);
	// $this->db->or_like('alamat', $q);
	// $this->db->or_like('jk', $q);
	// $this->db->or_like('email', $q);
	// $this->db->or_like('no_telp', $q);
	// $this->db->or_like('level', $q);
    $this->db->where('is_delete', $q='0');
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->set('is_delete', '1');
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

}

/* End of file Admin_model.php */
/* Location: ./application/models/Admin_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-31 14:24:22 */
/* http://harviacode.com */