<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/* 
 * Pagination Config Bootstrap 3 CSS Style
 * harviacode.com
 */

$config['query_string_segment'] = 'start';

$config['full_tag_open'] = '<nav><ul class="pagination" style="margin-top:0px">';
$config['full_tag_close'] = '</ul></nav>';



$config['next_link'] = '<button class="btn btn-warning">></button>';
$config['next_tag_open'] = '<li>';
$config['next_tag_close'] = '</li>';

$config['prev_link'] = '<button class="btn btn-warning"><</button>';
$config['prev_tag_open'] = '<li>';
$config['prev_tag_close'] = '</li>';

$config['cur_tag_open'] = '<li class="active"><a class="btn">';
$config['cur_tag_close'] = '</a></li>';

$config['num_tag_open'] = '<li class="btn">';
$config['num_tag_close'] = '</li>';


/* End of file pagination.php */
/* Location: ./application/config/pagination.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-09 21:39:15 */
/* http://harviacode.com */